#
# In this section you may indicate where the Haptic's SDK libraries are located
#

IF(VTKESQUI_USE_HAPTICS)

  # Add extra (Haptics) libs
  SET(KIT_LIBS ${KIT_LIBS} ${PROJECT_NAME}Haptics)
  SET(KIT_TCL_LIBS ${KIT_TCL_LIBS} ${PROJECT_NAME}HapticsTCL)
  SET(KIT_PYTHON_LIBS ${KIT_PYTHON_LIBS} ${PROJECT_NAME}HapticsPythonD)
  
  # Include haptic specific headers and librariess
  
  IF(LSWSDK_FOUND)
    INCLUDE_DIRECTORIES(${LSWSDK_INCLUDE_DIR})
    SET(KIT_LIBS ${KIT_LIBS} ${LSWSDK_LIBRARIES})
    SET(KIT_TCL_LIBS ${KIT_TCL_LIBS} ${LSWSDK_TCL_LIBRARIES})
    SET(KIT_PYTHON_LIBS ${KIT_PYTHON_LIBS} ${LSWSDK_PYTHON_LIBRARIES})
    LINK_DIRECTORIES( ${LINK_DIRECTORIES} ${LSWSDK_LIBRARY_DIR})
  ENDIF(LSWSDK_FOUND)
  
  IF(IHPSDK_FOUND)
    INCLUDE_DIRECTORIES(${IHPSDK_INCLUDE_DIR})
    SET(KIT_LIBS ${KIT_LIBS} ${IHPSDK_LIBRARIES})
    SET(KIT_TCL_LIBS ${KIT_TCL_LIBS} ${IHPSDK_TCL_LIBRARIES})
    SET(KIT_PYTHON_LIBS ${KIT_PYTHON_LIBS} ${IHPSDK_PYTHON_LIBRARIES})
    LINK_DIRECTORIES( ${LINK_DIRECTORIES} ${IHPSDK_LIBRARY_DIR})
  ENDIF(IHPSDK_FOUND)
  
  IF(VSPSDK_FOUND)
    INCLUDE_DIRECTORIES(${VSPSDK_INCLUDE_DIR})
    SET(KIT_LIBS ${KIT_LIBS} ${VSPSDK_LIBRARIES})
    SET(KIT_TCL_LIBS ${KIT_TCL_LIBS} ${VSPSDK_TCL_LIBRARIES})
    SET(KIT_PYTHON_LIBS ${KIT_PYTHON_LIBS} ${VSPSDK_PYTHON_LIBRARIES})
    LINK_DIRECTORIES( ${LINK_DIRECTORIES} ${VSPSDK_LIBRARY_DIR})
  ENDIF(VSPSDK_FOUND) 
  
  IF(SBMSDK_FOUND)
    INCLUDE_DIRECTORIES(${SBMSDK_INCLUDE_DIR})
    SET(KIT_LIBS ${KIT_LIBS} ${SBMSDK_LIBRARIES})
    SET(KIT_TCL_LIBS ${KIT_TCL_LIBS} ${SBMSDK_TCL_LIBRARIES})
    SET(KIT_PYTHON_LIBS ${KIT_PYTHON_LIBS} ${SBMSDK_PYTHON_LIBRARIES})
    LINK_DIRECTORIES( ${LINK_DIRECTORIES} ${SBMSDK_LIBRARY_DIR})
  ENDIF(SBMSDK_FOUND)
  
ENDIF(VTKESQUI_USE_HAPTICS)